[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.26"

[features]
resolution = true
skip-lint = false

[programs.devnet]
delta_neutral_vault = "C48TJDYWpws9dKu8bo8nq679w9vfCd7D1Emi9Abbhfyf"
lp_vault = "7UWS2aFyvNXiCHj1BTuWC7QU9iMBZcvjGBNABi7ByN4A"
meta_vault = "F4x55MUt2WXxqmtVQNyXBxg822pGUdge8KoYvuH6fLDQ"
staking_vault = "Bhmqob5GG4gBjEpJSYN17bGhWXnDS7rsrDH4UF7SduQ4"
yield_oracle = "CRZ13p9bH4hVcStuGFUZ1sjPf94J1q9H2fsGs5nCeoqG"
yield_vault = "5hp22e1bv9HG8QXZKE1YC48pgWZc1zNWdh3v1Z65h4zD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/devnet-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
